// Code generated by go generate; DO NOT EDIT.

package translation

import "slices"

type evaluator func(int) Key

type hint struct {
	Key  string
	Hint int
}

type definition struct {
	Evaluator evaluator
	Hints     []hint
}

var plurals = map[string]definition{
	"ar": {
		Evaluator: ArabicRule,
		Hints: []hint{
			{Key: "zero", Hint: 0},
			{Key: "one", Hint: 1},
			{Key: "two", Hint: 2},
			{Key: "few", Hint: 3},
			{Key: "many", Hint: 11},
			{Key: "other", Hint: 100},
		},
	},
	"az": {
		Evaluator: OtherRule,
		Hints: []hint{
			{Key: "other", Hint: 1},
		},
	},
	"be": {
		Evaluator: EastSlavicRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "few", Hint: 2},
			{Key: "many", Hint: 10},
			{Key: "other", Hint: 21},
		},
	},
	"bg": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"bn": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"bs": {
		Evaluator: OneFewOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "few", Hint: 2},
			{Key: "other", Hint: 12},
		},
	},
	"ca": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"cs": {
		Evaluator: WestSlavicRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "few", Hint: 2},
			{Key: "other", Hint: 5},
		},
	},
	"da": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"de": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"de-AT": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"de-CH": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"de-DE": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"el": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"el-CY": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"en": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"en-AU": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"en-CA": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"en-CY": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"en-GB": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"en-IE": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"en-IN": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"en-NZ": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"en-TT": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"en-US": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"en-ZA": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"eo": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"es": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"es-419": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"es-AR": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"es-CL": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"es-CO": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"es-CR": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"es-EC": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"es-ES": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"es-MX": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"es-NI": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"es-PA": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"es-PE": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"es-US": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"es-VE": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"et": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"eu": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"fa": {
		Evaluator: OtherRule,
		Hints: []hint{
			{Key: "other", Hint: 1},
		},
	},
	"fi": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"fr": {
		Evaluator: OneUptoTwoOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"fr-CA": {
		Evaluator: OneUptoTwoOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"fr-CH": {
		Evaluator: OneUptoTwoOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"fr-FR": {
		Evaluator: OneUptoTwoOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"fy": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"gd": {
		Evaluator: ScottishGaelicRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "two", Hint: 2},
			{Key: "few", Hint: 3},
			{Key: "other", Hint: 20},
		},
	},
	"gl": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"he": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"hi": {
		Evaluator: OneWithZeroOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"hi-IN": {
		Evaluator: OneWithZeroOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"hr": {
		Evaluator: OneFewOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "few", Hint: 2},
			{Key: "other", Hint: 12},
		},
	},
	"hsb": {
		Evaluator: UpperSorbianRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "two", Hint: 2},
			{Key: "few", Hint: 3},
			{Key: "other", Hint: 5},
		},
	},
	"hu": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"id": {
		Evaluator: OtherRule,
		Hints: []hint{
			{Key: "other", Hint: 1},
		},
	},
	"is": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"it": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"it-CH": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"ja": {
		Evaluator: OtherRule,
		Hints: []hint{
			{Key: "other", Hint: 1},
		},
	},
	"ka": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"kk": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"km": {
		Evaluator: OtherRule,
		Hints: []hint{
			{Key: "other", Hint: 1},
		},
	},
	"kn": {
		Evaluator: OtherRule,
		Hints: []hint{
			{Key: "other", Hint: 1},
		},
	},
	"ko": {
		Evaluator: OtherRule,
		Hints: []hint{
			{Key: "other", Hint: 1},
		},
	},
	"lo": {
		Evaluator: OtherRule,
		Hints: []hint{
			{Key: "other", Hint: 1},
		},
	},
	"lt": {
		Evaluator: LithuanianRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "few", Hint: 2},
			{Key: "other", Hint: 11},
		},
	},
	"lv": {
		Evaluator: LatvianRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"mg": {
		Evaluator: OneWithZeroOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"mk": {
		Evaluator: MacedonianRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"ml": {
		Evaluator: OneWithZeroOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"mn": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"mr-IN": {
		Evaluator: OneWithZeroOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"ms": {
		Evaluator: OtherRule,
		Hints: []hint{
			{Key: "other", Hint: 1},
		},
	},
	"nb": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"ne": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"nl": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"nn": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"oc": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"or": {
		Evaluator: OneWithZeroOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"pa": {
		Evaluator: OneWithZeroOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"pap-AW": {
		Evaluator: OtherRule,
		Hints: []hint{
			{Key: "other", Hint: 1},
		},
	},
	"pap-CW": {
		Evaluator: OtherRule,
		Hints: []hint{
			{Key: "other", Hint: 1},
		},
	},
	"pl": {
		Evaluator: PolishRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "few", Hint: 2},
			{Key: "many", Hint: 10},
			{Key: "other", Hint: 12},
		},
	},
	"pt": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"pt-BR": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"ro": {
		Evaluator: RomanianRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "few", Hint: 2},
			{Key: "other", Hint: 20},
		},
	},
	"ru": {
		Evaluator: EastSlavicRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "few", Hint: 2},
			{Key: "many", Hint: 10},
			{Key: "other", Hint: 21},
		},
	},
	"sc": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"sk": {
		Evaluator: WestSlavicRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "few", Hint: 2},
			{Key: "other", Hint: 5},
		},
	},
	"sl": {
		Evaluator: SlovenianRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "two", Hint: 2},
			{Key: "few", Hint: 3},
			{Key: "other", Hint: 5},
		},
	},
	"sr": {
		Evaluator: OneFewOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "few", Hint: 2},
			{Key: "other", Hint: 12},
		},
	},
	"st": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"sv": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"sv-SE": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"sw": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"ta": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"th": {
		Evaluator: OtherRule,
		Hints: []hint{
			{Key: "other", Hint: 1},
		},
	},
	"tl": {
		Evaluator: OneWithZeroOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"tr": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"uk": {
		Evaluator: EastSlavicRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "few", Hint: 2},
			{Key: "many", Hint: 10},
			{Key: "other", Hint: 21},
		},
	},
	"ur": {
		Evaluator: OneOtherRule,
		Hints: []hint{
			{Key: "one", Hint: 1},
			{Key: "other", Hint: 2},
		},
	},
	"vi": {
		Evaluator: OtherRule,
		Hints: []hint{
			{Key: "other", Hint: 1},
		},
	},
	"wo": {
		Evaluator: OtherRule,
		Hints: []hint{
			{Key: "other", Hint: 1},
		},
	},
	"zh-CN": {
		Evaluator: OtherRule,
		Hints: []hint{
			{Key: "other", Hint: 1},
		},
	},
	"zh-HK": {
		Evaluator: OtherRule,
		Hints: []hint{
			{Key: "other", Hint: 1},
		},
	},
	"zh-TW": {
		Evaluator: OtherRule,
		Hints: []hint{
			{Key: "other", Hint: 1},
		},
	},
	"zh-YUE": {
		Evaluator: OtherRule,
		Hints: []hint{
			{Key: "other", Hint: 1},
		},
	},
}

type Key string

const (
	Zero  Key = "zero"
	One   Key = "one"
	Two   Key = "two"
	Few   Key = "few"
	Many  Key = "many"
	Other Key = "other"
)

func isBetween(min, max, value int) bool {
	return min <= value && value <= max
}

func ArabicRule(count int) Key {
	mod100 := count % 100

	if count == 0 {
		return Zero
	} else if count == 1 {
		return One
	} else if count == 2 {
		return Two
	} else if isBetween(3, 10, mod100) {
		return Few
	} else if isBetween(11, 99, mod100) {
		return Many
	}

	return Other
}

func EastSlavicRule(count int) Key {
	mod10 := count % 10
	mod100 := count % 100

	if mod10 == 1 && mod100 != 11 {
		return One
	} else if isBetween(2, 4, mod10) && !isBetween(12, 14, mod100) {
		return Few
	} else if mod10 == 0 || isBetween(5, 9, mod10) || isBetween(11, 14, mod100) {
		return Many
	}

	return Other
}

func LatvianRule(count int) Key {
	if count%10 == 1 && count%100 != 11 {
		return One
	}

	return Other
}

func LithuanianRule(count int) Key {
	mod10 := count % 10
	mod100 := count % 100

	if mod10 == 1 && !isBetween(11, 19, mod100) {
		return One
	} else if isBetween(2, 9, mod10) && !isBetween(11, 19, mod100) {
		return Few
	}

	return Other
}

func MacedonianRule(count int) Key {
	if count%10 == 1 && count != 11 {
		return One
	}

	return Other
}

func OneFewOtherRule(count int) Key {
	mod10 := count % 10
	mod100 := count % 100

	if mod10 == 1 && mod100 != 11 {
		return One
	} else if isBetween(2, 4, mod10) && !isBetween(12, 14, mod100) {
		return Few
	}

	return Other
}

func OneOtherRule(count int) Key {
	if count == 1 {
		return One
	}

	return Other
}

func OneUptoTwoOtherRule(count int) Key {
	if count >= 0 && count < 2 {
		return One
	}

	return Other
}

func OneWithZeroOtherRule(count int) Key {
	switch count {
	case 0, 1:
		return One
	default:
		return Other
	}
}

func OtherRule(count int) Key {
	return Other
}

func PolishRule(count int) Key {
	mod10 := count % 10
	mod100 := count % 100

	if count == 1 {
		return One
	} else if isBetween(2, 4, mod10) && !isBetween(12, 14, mod100) {
		return Few
	} else if slices.Index([]int{0, 1, 5, 6, 7, 8, 9}, mod10) != -1 || isBetween(12, 14, mod100) {
		return Many
	}

	return Other
}

func RomanianRule(count int) Key {
	if count == 1 {
		return One
	} else if count == 0 || isBetween(1, 19, count%100) {
		return Few
	}

	return Other
}

func ScottishGaelicRule(count int) Key {
	if count == 1 || count == 11 {
		return One
	} else if count == 2 || count == 12 {
		return Two
	} else if isBetween(3, 19, count) {
		return Few
	}

	return Other
}

func SlovenianRule(count int) Key {
	switch count % 100 {
	case 1:
		return One
	case 2:
		return Two
	case 3, 4:
		return Few
	default:
		return Other
	}
}

func UpperSorbianRule(count int) Key {
	mod100 := count % 100

	switch mod100 {
	case 1:
		return One
	case 2:
		return Two
	case 3, 4:
		return Few
	default:
		return Other
	}
}

func WestSlavicRule(count int) Key {
	switch count {
	case 1:
		return One
	case 2, 3, 4:
		return Few
	default:
		return Other
	}
}
